apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-lerncloud-multipass
  namespace: mc-b
  description: LernCloud Terraform Module fuer Multipass
  tags: 
  - terraform
  - lerncloud
  - opentofu    
  - multipass
  links:
  - url: https://github.com/mc-b/terraform-lerncloud-multipass
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/terraform-lerncloud-multipass
    backstage.io/source-location: url:https://github.com/mc-b/terraform-lerncloud-multipass
    # backstage.io/techdocs-ref: url:https://github.com/mc-b/terraform-lerncloud-multipass
spec:
  type: infrastructure
  lifecycle: experimental
  owner: group:mc-b/mc-b
  subcomponentOf: component:mc-b/terraform-provider-lerncloud
  
